<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Capítulo 1 Modelo lineal simple | Notas de clase: Modelo lineal general I</title>
  <meta name="description" content="Capítulo 1 Modelo lineal simple | Notas de clase: Modelo lineal general I" />
  <meta name="generator" content="bookdown 0.22 and GitBook 2.6.7" />

  <meta property="og:title" content="Capítulo 1 Modelo lineal simple | Notas de clase: Modelo lineal general I" />
  <meta property="og:type" content="book" />
  
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Capítulo 1 Modelo lineal simple | Notas de clase: Modelo lineal general I" />
  
  
  

<meta name="author" content="Alvaro J. Flórez" />


<meta name="date" content="2021-08-12" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="index.html"/>
<link rel="next" href="modelo-lineal-múltiple.html"/>
<script src="libs/header-attrs-2.7/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Notas de clase MLGI</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Introducción</a></li>
<li class="chapter" data-level="1" data-path="modelo-lineal-simple.html"><a href="modelo-lineal-simple.html"><i class="fa fa-check"></i><b>1</b> Modelo lineal simple</a>
<ul>
<li class="chapter" data-level="" data-path="modelo-lineal-simple.html"><a href="modelo-lineal-simple.html#datos-de-peso-al-nacer"><i class="fa fa-check"></i>Datos de peso al nacer</a></li>
<li class="chapter" data-level="1.1" data-path="modelo-lineal-simple.html"><a href="modelo-lineal-simple.html#regresion-lineal-simple"><i class="fa fa-check"></i><b>1.1</b> Regresion lineal simple</a></li>
<li class="chapter" data-level="1.2" data-path="modelo-lineal-simple.html"><a href="modelo-lineal-simple.html#modelo-lineal-simple-1"><i class="fa fa-check"></i><b>1.2</b> Modelo lineal simple</a></li>
<li class="chapter" data-level="1.3" data-path="modelo-lineal-simple.html"><a href="modelo-lineal-simple.html#estimación-de-los-parámetros"><i class="fa fa-check"></i><b>1.3</b> Estimación de los parámetros</a></li>
<li class="chapter" data-level="1.4" data-path="modelo-lineal-simple.html"><a href="modelo-lineal-simple.html#estimación-de-sigma2"><i class="fa fa-check"></i><b>1.4</b> Estimación de <span class="math inline">\(\sigma^{2}\)</span></a>
<ul>
<li class="chapter" data-level="" data-path="modelo-lineal-simple.html"><a href="modelo-lineal-simple.html#datos-de-peso-al-nacer.-modelo-y-estimación-de-parametros"><i class="fa fa-check"></i>Datos de peso al nacer. Modelo y estimación de parametros</a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="modelo-lineal-simple.html"><a href="modelo-lineal-simple.html#propiedades-de-los-estimadores-por-mco"><i class="fa fa-check"></i><b>1.5</b> Propiedades de los estimadores por MCO</a></li>
<li class="chapter" data-level="1.6" data-path="modelo-lineal-simple.html"><a href="modelo-lineal-simple.html#inferencia"><i class="fa fa-check"></i><b>1.6</b> Inferencia</a>
<ul>
<li class="chapter" data-level="1.6.1" data-path="modelo-lineal-simple.html"><a href="modelo-lineal-simple.html#pruebas-de-hipótesis"><i class="fa fa-check"></i><b>1.6.1</b> Pruebas de hipótesis</a></li>
<li class="chapter" data-level="1.6.2" data-path="modelo-lineal-simple.html"><a href="modelo-lineal-simple.html#análisis-de-varianza"><i class="fa fa-check"></i><b>1.6.2</b> Análisis de varianza</a></li>
<li class="chapter" data-level="" data-path="modelo-lineal-simple.html"><a href="modelo-lineal-simple.html#datos-de-peso-al-nacer.-pruebas-de-hipótesis-y-anova"><i class="fa fa-check"></i>Datos de peso al nacer. Pruebas de hipótesis y ANOVA</a></li>
<li class="chapter" data-level="1.6.3" data-path="modelo-lineal-simple.html"><a href="modelo-lineal-simple.html#intervalos-de-confianza"><i class="fa fa-check"></i><b>1.6.3</b> Intervalos de confianza</a></li>
<li class="chapter" data-level="" data-path="modelo-lineal-simple.html"><a href="modelo-lineal-simple.html#datos-de-peso-al-nacer.-intervalos-de-confianza"><i class="fa fa-check"></i>Datos de peso al nacer. Intervalos de confianza</a></li>
</ul></li>
<li class="chapter" data-level="1.7" data-path="modelo-lineal-simple.html"><a href="modelo-lineal-simple.html#estimador-por-máxima-verosimilitud"><i class="fa fa-check"></i><b>1.7</b> Estimador por máxima verosimilitud</a></li>
<li class="chapter" data-level="1.8" data-path="modelo-lineal-simple.html"><a href="modelo-lineal-simple.html#algunas-consideraciones-finales"><i class="fa fa-check"></i><b>1.8</b> Algunas consideraciones finales</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="modelo-lineal-múltiple.html"><a href="modelo-lineal-múltiple.html"><i class="fa fa-check"></i><b>2</b> Modelo lineal múltiple</a>
<ul>
<li class="chapter" data-level="" data-path="modelo-lineal-múltiple.html"><a href="modelo-lineal-múltiple.html#bajo-peso-al-nacer"><i class="fa fa-check"></i>Bajo peso al nacer</a></li>
<li class="chapter" data-level="2.1" data-path="modelo-lineal-múltiple.html"><a href="modelo-lineal-múltiple.html#modelo-lineal-múltiple-1"><i class="fa fa-check"></i><b>2.1</b> Modelo lineal múltiple</a></li>
<li class="chapter" data-level="2.2" data-path="modelo-lineal-múltiple.html"><a href="modelo-lineal-múltiple.html#estimación-de-los-parámetros-de-regresión"><i class="fa fa-check"></i><b>2.2</b> Estimación de los parámetros de regresión</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="modelo-lineal-múltiple.html"><a href="modelo-lineal-múltiple.html#estimación-de-sigma2-1"><i class="fa fa-check"></i><b>2.2.1</b> Estimación de <span class="math inline">\(\sigma^{2}\)</span></a></li>
<li class="chapter" data-level="2.2.2" data-path="modelo-lineal-múltiple.html"><a href="modelo-lineal-múltiple.html#bajo-peso-al-nacer---estimación-de-parámetros"><i class="fa fa-check"></i><b>2.2.2</b> Bajo peso al nacer - estimación de parámetros</a></li>
<li class="chapter" data-level="2.2.3" data-path="modelo-lineal-múltiple.html"><a href="modelo-lineal-múltiple.html#propiedades-de-los-estimadores-por-mco-1"><i class="fa fa-check"></i><b>2.2.3</b> Propiedades de los estimadores por MCO</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="modelo-lineal-múltiple.html"><a href="modelo-lineal-múltiple.html#pruebas-de-hipótesis-1"><i class="fa fa-check"></i><b>2.3</b> Pruebas de hipótesis</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="modelo-lineal-múltiple.html"><a href="modelo-lineal-múltiple.html#análisis-de-varianza-1"><i class="fa fa-check"></i><b>2.3.1</b> Análisis de varianza</a></li>
<li class="chapter" data-level="2.3.2" data-path="modelo-lineal-múltiple.html"><a href="modelo-lineal-múltiple.html#pruebas-individuales-sobre-los-coeficientes"><i class="fa fa-check"></i><b>2.3.2</b> Pruebas individuales sobre los coeficientes</a></li>
<li class="chapter" data-level="2.3.3" data-path="modelo-lineal-múltiple.html"><a href="modelo-lineal-múltiple.html#pruebas-sobre-subconjuntos-de-coeficientes"><i class="fa fa-check"></i><b>2.3.3</b> Pruebas sobre subconjuntos de coeficientes</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="modelo-lineal-múltiple.html"><a href="modelo-lineal-múltiple.html#prueba-de-hipótesis-lineal-general"><i class="fa fa-check"></i><b>2.4</b> Prueba de hipótesis lineal general</a>
<ul>
<li class="chapter" data-level="" data-path="modelo-lineal-múltiple.html"><a href="modelo-lineal-múltiple.html#bajo-peso-al-nacer---pruebas-de-hipótesis"><i class="fa fa-check"></i>Bajo peso al nacer - pruebas de hipótesis</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="modelo-lineal-múltiple.html"><a href="modelo-lineal-múltiple.html#intervalos-de-confianza-1"><i class="fa fa-check"></i><b>2.5</b> Intervalos de confianza</a>
<ul>
<li class="chapter" data-level="2.5.1" data-path="modelo-lineal-múltiple.html"><a href="modelo-lineal-múltiple.html#intervalos-de-confianza-para-beta_j"><i class="fa fa-check"></i><b>2.5.1</b> Intervalos de confianza para <span class="math inline">\(\beta_{j}\)</span></a></li>
<li class="chapter" data-level="2.5.2" data-path="modelo-lineal-múltiple.html"><a href="modelo-lineal-múltiple.html#intervalos-de-confianza-para-el-valor-esperado-de-y-y-una-observación-futura"><i class="fa fa-check"></i><b>2.5.2</b> Intervalos de confianza para el valor esperado de <span class="math inline">\(Y\)</span> y una observación futura</a></li>
<li class="chapter" data-level="" data-path="modelo-lineal-múltiple.html"><a href="modelo-lineal-múltiple.html#bajo-peso-al-nacer---intervalos-de-confianza"><i class="fa fa-check"></i>Bajo peso al nacer - intervalos de confianza</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="modelo-lineal-múltiple.html"><a href="modelo-lineal-múltiple.html#extrapolación-oculta-en-regresión-múltiple"><i class="fa fa-check"></i><b>2.6</b> Extrapolación oculta en regresión múltiple</a>
<ul>
<li class="chapter" data-level="" data-path="modelo-lineal-múltiple.html"><a href="modelo-lineal-múltiple.html#bajo-peso-al-nacer---interpolación"><i class="fa fa-check"></i>Bajo peso al nacer - interpolación</a></li>
<li class="chapter" data-level="2.6.1" data-path="modelo-lineal-múltiple.html"><a href="modelo-lineal-múltiple.html#coeficientes-normalizados-de-regresión"><i class="fa fa-check"></i><b>2.6.1</b> Coeficientes normalizados de regresión</a></li>
<li class="chapter" data-level="" data-path="modelo-lineal-múltiple.html"><a href="modelo-lineal-múltiple.html#bajo-peso-al-nacer---coeficientes-de-regresión-con-variables-escaladas"><i class="fa fa-check"></i>Bajo peso al nacer - coeficientes de regresión con variables escaladas</a></li>
</ul></li>
<li class="chapter" data-level="2.7" data-path="modelo-lineal-múltiple.html"><a href="modelo-lineal-múltiple.html#multicolinealidad"><i class="fa fa-check"></i><b>2.7</b> Multicolinealidad</a>
<ul>
<li class="chapter" data-level="" data-path="modelo-lineal-múltiple.html"><a href="modelo-lineal-múltiple.html#ejemplo-2"><i class="fa fa-check"></i>ejemplo</a></li>
<li class="chapter" data-level="2.7.1" data-path="modelo-lineal-múltiple.html"><a href="modelo-lineal-múltiple.html#bajo-peso-al-nacer---factores-de-inflación-de-varianza"><i class="fa fa-check"></i><b>2.7.1</b> Bajo peso al nacer - factores de inflación de varianza</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="evaluación-de-los-supuestos-del-modelo.html"><a href="evaluación-de-los-supuestos-del-modelo.html"><i class="fa fa-check"></i><b>3</b> Evaluación de los supuestos del modelo</a>
<ul>
<li class="chapter" data-level="" data-path="evaluación-de-los-supuestos-del-modelo.html"><a href="evaluación-de-los-supuestos-del-modelo.html#ejemplo-1.-datos-de-peso-al-nacer"><i class="fa fa-check"></i>Ejemplo 1. Datos de peso al nacer</a></li>
<li class="chapter" data-level="" data-path="evaluación-de-los-supuestos-del-modelo.html"><a href="evaluación-de-los-supuestos-del-modelo.html#ejemplo-2.-ventas-de-helados"><i class="fa fa-check"></i>Ejemplo 2. Ventas de helados</a></li>
<li class="chapter" data-level="" data-path="evaluación-de-los-supuestos-del-modelo.html"><a href="evaluación-de-los-supuestos-del-modelo.html#ejemplo-3.-longitud-del-pez-lobina-boca-chica"><i class="fa fa-check"></i>Ejemplo 3. Longitud del pez lobina boca chica</a></li>
<li class="chapter" data-level="3.1" data-path="evaluación-de-los-supuestos-del-modelo.html"><a href="evaluación-de-los-supuestos-del-modelo.html#supuestos-del-modelo-linea-múltiple"><i class="fa fa-check"></i><b>3.1</b> Supuestos del modelo linea múltiple</a></li>
<li class="chapter" data-level="3.2" data-path="evaluación-de-los-supuestos-del-modelo.html"><a href="evaluación-de-los-supuestos-del-modelo.html#efectos-del-incumplimiento-de-los-supuestos"><i class="fa fa-check"></i><b>3.2</b> Efectos del incumplimiento de los supuestos</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="evaluación-de-los-supuestos-del-modelo.html"><a href="evaluación-de-los-supuestos-del-modelo.html#sesgo-por-omisión-de-variables-relevantes"><i class="fa fa-check"></i><b>3.2.1</b> Sesgo por omisión de variables relevantes</a></li>
<li class="chapter" data-level="3.2.2" data-path="evaluación-de-los-supuestos-del-modelo.html"><a href="evaluación-de-los-supuestos-del-modelo.html#incorrecta-matriz-de-varianzas-de-los-errores"><i class="fa fa-check"></i><b>3.2.2</b> Incorrecta matriz de varianzas de los errores</a></li>
<li class="chapter" data-level="3.2.3" data-path="evaluación-de-los-supuestos-del-modelo.html"><a href="evaluación-de-los-supuestos-del-modelo.html#distribución-no-normal-de-los-errores"><i class="fa fa-check"></i><b>3.2.3</b> Distribución no normal de los errores</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="evaluación-de-los-supuestos-del-modelo.html"><a href="evaluación-de-los-supuestos-del-modelo.html#residuos-del-modelo"><i class="fa fa-check"></i><b>3.3</b> Residuos del modelo</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="evaluación-de-los-supuestos-del-modelo.html"><a href="evaluación-de-los-supuestos-del-modelo.html#residuos-estudentizados"><i class="fa fa-check"></i><b>3.3.1</b> Residuos estudentizados</a></li>
<li class="chapter" data-level="3.3.2" data-path="evaluación-de-los-supuestos-del-modelo.html"><a href="evaluación-de-los-supuestos-del-modelo.html#residuos-press-y-r-student"><i class="fa fa-check"></i><b>3.3.2</b> Residuos PRESS y R-student</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="evaluación-de-los-supuestos-del-modelo.html"><a href="evaluación-de-los-supuestos-del-modelo.html#evaluación-del-cumplimiento-de-los-supuestos"><i class="fa fa-check"></i><b>3.4</b> Evaluación del cumplimiento de los supuestos</a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="evaluación-de-los-supuestos-del-modelo.html"><a href="evaluación-de-los-supuestos-del-modelo.html#gráficos-de-residuos"><i class="fa fa-check"></i><b>3.4.1</b> Gráficos de residuos</a></li>
<li class="chapter" data-level="3.4.2" data-path="evaluación-de-los-supuestos-del-modelo.html"><a href="evaluación-de-los-supuestos-del-modelo.html#gráficos-de-residuos-parciales"><i class="fa fa-check"></i><b>3.4.2</b> Gráficos de residuos parciales</a></li>
<li class="chapter" data-level="3.4.3" data-path="evaluación-de-los-supuestos-del-modelo.html"><a href="evaluación-de-los-supuestos-del-modelo.html#gráficos-de-normalidad"><i class="fa fa-check"></i><b>3.4.3</b> Gráficos de normalidad</a></li>
<li class="chapter" data-level="3.4.4" data-path="evaluación-de-los-supuestos-del-modelo.html"><a href="evaluación-de-los-supuestos-del-modelo.html#gráfico-de-residuos-frente-a-el-tiempo"><i class="fa fa-check"></i><b>3.4.4</b> Gráfico de residuos frente a el tiempo</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="evaluación-de-los-supuestos-del-modelo.html"><a href="evaluación-de-los-supuestos-del-modelo.html#pruebas-de-hipótesis-para-evaluar-los-supuestos"><i class="fa fa-check"></i><b>3.5</b> Pruebas de hipótesis para evaluar los supuestos</a>
<ul>
<li class="chapter" data-level="3.5.1" data-path="evaluación-de-los-supuestos-del-modelo.html"><a href="evaluación-de-los-supuestos-del-modelo.html#prueba-de-falta-de-ajuste"><i class="fa fa-check"></i><b>3.5.1</b> Prueba de falta de ajuste</a></li>
<li class="chapter" data-level="3.5.2" data-path="evaluación-de-los-supuestos-del-modelo.html"><a href="evaluación-de-los-supuestos-del-modelo.html#prueba-de-heterocedasticidad"><i class="fa fa-check"></i><b>3.5.2</b> Prueba de heterocedasticidad</a></li>
<li class="chapter" data-level="3.5.3" data-path="evaluación-de-los-supuestos-del-modelo.html"><a href="evaluación-de-los-supuestos-del-modelo.html#prueba-de-normalidad"><i class="fa fa-check"></i><b>3.5.3</b> Prueba de normalidad</a></li>
<li class="chapter" data-level="3.5.4" data-path="evaluación-de-los-supuestos-del-modelo.html"><a href="evaluación-de-los-supuestos-del-modelo.html#prueba-de-correlación-temporal-de-los-errores"><i class="fa fa-check"></i><b>3.5.4</b> Prueba de correlación temporal de los errores</a></li>
</ul></li>
<li class="chapter" data-level="3.6" data-path="evaluación-de-los-supuestos-del-modelo.html"><a href="evaluación-de-los-supuestos-del-modelo.html#comentarios-finales"><i class="fa fa-check"></i><b>3.6</b> Comentarios finales</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="transformaciones-y-mínimos-cuadrados-ponderados.html"><a href="transformaciones-y-mínimos-cuadrados-ponderados.html"><i class="fa fa-check"></i><b>4</b> Transformaciones y mínimos cuadrados ponderados</a>
<ul>
<li class="chapter" data-level="" data-path="transformaciones-y-mínimos-cuadrados-ponderados.html"><a href="transformaciones-y-mínimos-cuadrados-ponderados.html#ejemplo-1.-datos-de-la-onu"><i class="fa fa-check"></i>Ejemplo 1. Datos de la ONU</a></li>
<li class="chapter" data-level="" data-path="transformaciones-y-mínimos-cuadrados-ponderados.html"><a href="transformaciones-y-mínimos-cuadrados-ponderados.html#ejemplo-2.-datos-de-educación"><i class="fa fa-check"></i>Ejemplo 2. Datos de educación</a></li>
<li class="chapter" data-level="4.1" data-path="transformaciones-y-mínimos-cuadrados-ponderados.html"><a href="transformaciones-y-mínimos-cuadrados-ponderados.html#transformación-de-los-datos"><i class="fa fa-check"></i><b>4.1</b> Transformación de los datos</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="transformaciones-y-mínimos-cuadrados-ponderados.html"><a href="transformaciones-y-mínimos-cuadrados-ponderados.html#transformaciones-para-linealizar-el-modelo"><i class="fa fa-check"></i><b>4.1.1</b> Transformaciones para linealizar el modelo</a></li>
<li class="chapter" data-level="4.1.2" data-path="transformaciones-y-mínimos-cuadrados-ponderados.html"><a href="transformaciones-y-mínimos-cuadrados-ponderados.html#transformaciones-para-estabilizar-la-varianza"><i class="fa fa-check"></i><b>4.1.2</b> Transformaciones para estabilizar la varianza</a></li>
<li class="chapter" data-level="" data-path="transformaciones-y-mínimos-cuadrados-ponderados.html"><a href="transformaciones-y-mínimos-cuadrados-ponderados.html#datos-de-la-onu.-transformación-para-linealizar-los-datos"><i class="fa fa-check"></i>Datos de la ONU. Transformación para linealizar los datos</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="transformaciones-y-mínimos-cuadrados-ponderados.html"><a href="transformaciones-y-mínimos-cuadrados-ponderados.html#método-de-box-cox"><i class="fa fa-check"></i><b>4.2</b> Método de Box-Cox</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="transformaciones-y-mínimos-cuadrados-ponderados.html"><a href="transformaciones-y-mínimos-cuadrados-ponderados.html#datos-de-educación.-transformación-de-box-cox"><i class="fa fa-check"></i><b>4.2.1</b> Datos de educación. Transformación de Box-Cox</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="transformaciones-y-mínimos-cuadrados-ponderados.html"><a href="transformaciones-y-mínimos-cuadrados-ponderados.html#mínimos-cuadrados-ponderados"><i class="fa fa-check"></i><b>4.3</b> Mínimos cuadrados ponderados</a>
<ul>
<li class="chapter" data-level="" data-path="transformaciones-y-mínimos-cuadrados-ponderados.html"><a href="transformaciones-y-mínimos-cuadrados-ponderados.html#datos-de-educación.-minímos-cuadrados-ponderados"><i class="fa fa-check"></i>Datos de educación. Minímos cuadrados ponderados</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="evaluación-de-puntos-influyentes-y-atípicos.html"><a href="evaluación-de-puntos-influyentes-y-atípicos.html"><i class="fa fa-check"></i><b>5</b> Evaluación de puntos influyentes y atípicos</a>
<ul>
<li class="chapter" data-level="5.1" data-path="evaluación-de-puntos-influyentes-y-atípicos.html"><a href="evaluación-de-puntos-influyentes-y-atípicos.html#datos-de-la-onu"><i class="fa fa-check"></i><b>5.1</b> Datos de la ONU</a></li>
<li class="chapter" data-level="5.2" data-path="evaluación-de-puntos-influyentes-y-atípicos.html"><a href="evaluación-de-puntos-influyentes-y-atípicos.html#importancia-de-detectar-valores-influyentes-y-atípicos"><i class="fa fa-check"></i><b>5.2</b> Importancia de detectar valores influyentes y atípicos</a></li>
<li class="chapter" data-level="5.3" data-path="evaluación-de-puntos-influyentes-y-atípicos.html"><a href="evaluación-de-puntos-influyentes-y-atípicos.html#valores-atípicos"><i class="fa fa-check"></i><b>5.3</b> Valores atípicos</a>
<ul>
<li class="chapter" data-level="" data-path="evaluación-de-puntos-influyentes-y-atípicos.html"><a href="evaluación-de-puntos-influyentes-y-atípicos.html#datos-de-la-onu---valores-atípicos"><i class="fa fa-check"></i>Datos de la ONU - valores atípicos</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="evaluación-de-puntos-influyentes-y-atípicos.html"><a href="evaluación-de-puntos-influyentes-y-atípicos.html#puntos-de-balanceo"><i class="fa fa-check"></i><b>5.4</b> Puntos de balanceo</a>
<ul>
<li class="chapter" data-level="" data-path="evaluación-de-puntos-influyentes-y-atípicos.html"><a href="evaluación-de-puntos-influyentes-y-atípicos.html#datos-de-la-onu---diagonal-de-la-matrix-hat"><i class="fa fa-check"></i>Datos de la ONU - diagonal de la matrix hat</a></li>
<li class="chapter" data-level="5.4.1" data-path="evaluación-de-puntos-influyentes-y-atípicos.html"><a href="evaluación-de-puntos-influyentes-y-atípicos.html#medidas-de-influencia"><i class="fa fa-check"></i><b>5.4.1</b> Medidas de influencia</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="evaluación-de-puntos-influyentes-y-atípicos.html"><a href="evaluación-de-puntos-influyentes-y-atípicos.html#comentarios-finales-1"><i class="fa fa-check"></i><b>5.5</b> Comentarios finales</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Notas de clase: Modelo lineal general I</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="modelo-lineal-simple" class="section level1" number="1">
<h1><span class="header-section-number">Capítulo 1</span> Modelo lineal simple</h1>
<div id="datos-de-peso-al-nacer" class="section level2 unnumbered">
<h2>Datos de peso al nacer</h2>
<p>Los datos <code>birthweight</code> (disponible en el campus virtual) contienen el peso y la edad gestacional de <span class="math inline">\(42\)</span> recién nacidos. El objetivo del estudio es investigar cómo la edad gestational del feto influyen en el peso al nacer durante las últimas semanas del embarazo. Aunque la base de datos contiene otras variables, por ahora solo consideramos el peso y la edad gestacional.</p>
<p>La Figura <a href="modelo-lineal-simple.html#fig:birthweightFigure">1.1</a> muestra la relación entre el peso (en kilogramos) y la edad gestacional (en semanas) del recién nacido. Por medio de este gráfico vemos que hay una relación aproximadamente lineal positiva (la correlación es igual a 0.73). Es decir que cuando la edad gestacional aumenta, el peso del recién nacido también lo hace. Por lo tanto, sería razonable describir el valor esperado del peso al nacer como una función lineal de la edad gestacional:
<span class="math display">\[
E(\mbox{weight}|\mbox{age}=x) = \beta_{0} + \beta_{1}x.
\]</span></p>
<p>La Figura <a href="modelo-lineal-simple.html#fig:birthweightFigure">1.1</a> se puede hacer con el siguiente código:</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="modelo-lineal-simple.html#cb1-1" aria-hidden="true" tabindex="-1"></a>birthweight <span class="ot">=</span> <span class="fu">read.csv</span>(<span class="st">&quot;birthweight.csv&quot;</span>,<span class="at">header =</span> T)</span>
<span id="cb1-2"><a href="modelo-lineal-simple.html#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="modelo-lineal-simple.html#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(weight<span class="sc">~</span>age,<span class="at">data=</span>birthweight,<span class="at">pch=</span><span class="dv">20</span>,<span class="at">xlab=</span><span class="st">&quot;Edad gestacional(semanas)&quot;</span>,</span>
<span id="cb1-4"><a href="modelo-lineal-simple.html#cb1-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab=</span><span class="st">&#39;Peso(kilogramos)&#39;</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:birthweightFigure"></span>
<img src="bookdownproj_files/figure-html/birthweightFigure-1.png" alt="Gráfico de dispersion del peso del recien nacido y la edad gestacional." width="480" />
<p class="caption">
Figure 1.1: Gráfico de dispersion del peso del recien nacido y la edad gestacional.
</p>
</div>
<p>Con este conjunto de datos podemos plantear las siguientes preguntas:</p>
<ul>
<li>¿Cómo afecta la edad gestional al peso del neonato?</li>
<li>Si la edad gestacional aumenta en una unidad ¿en cuanto aumenta el peso del recién nacido? ¿ese aumento puede considerarse significativo?</li>
<li>¿Se puede predecir el peso al nacer por medio de la edad gestacional?</li>
</ul>
<p>Estas preguntas se pueden resolver a partir de un análisis de regresión lineal.</p>
</div>
<div id="regresion-lineal-simple" class="section level2" number="1.1">
<h2><span class="header-section-number">1.1</span> Regresion lineal simple</h2>
<p>En una análisis de regresión simple estamos interesados en modelar la relación entre una variable de entrada (regresor, variable independiente o covariable) <span class="math inline">\(X\)</span> y una variable de salida (respuesta o variable dependiente) <span class="math inline">\(Y\)</span>.</p>
<p>El modelo de regresión nos permite:</p>
<ul>
<li>Evaluar cuanto cambia el valor esperado de <span class="math inline">\(Y\)</span> debido a cambios en <span class="math inline">\(X\)</span>,</li>
<li>Predecir <span class="math inline">\(Y\)</span> (o su valor esperado) en función de <span class="math inline">\(X\)</span>.</li>
</ul>
</div>
<div id="modelo-lineal-simple-1" class="section level2" number="1.2">
<h2><span class="header-section-number">1.2</span> Modelo lineal simple</h2>
<p>Sea <span class="math inline">\((y_{i},x_{i})\)</span> la i-ésima observación de la variable respuesta <span class="math inline">\((y)\)</span> y la covariable <span class="math inline">\((x)\)</span>, para <span class="math inline">\(i=1,\ldots,n\)</span>, con <span class="math inline">\(n\)</span> igual al número total de observaciones. <strong>El modelo lineal simple</strong> se puede expresar de la forma:
<span class="math display">\[
y_{i} = \beta_{0} + \beta_{1}x_{i}+\varepsilon_{i},
\]</span>
donde <span class="math inline">\(\beta_{0}\)</span> es el intercepto, <span class="math inline">\(\beta_{1}\)</span> es la pendiente y <span class="math inline">\(\varepsilon_{i}\)</span> es el componente de error. Generalmente, los supuestos que acompañan este modelo son:</p>
<ol style="list-style-type: lower-alpha">
<li><span class="math inline">\(E(\varepsilon_{i}) = 0\)</span>,</li>
<li><span class="math inline">\(V(\varepsilon_{i}) = \sigma^{2}\)</span>,</li>
<li><span class="math inline">\(cov(\varepsilon_{i},\varepsilon_{j}) = 0\)</span>, para todo <span class="math inline">\(i \neq j\)</span>,</li>
<li><span class="math inline">\(\varepsilon_{i}\)</span> se distribuye normalmente.</li>
</ol>
<p>Por lo tanto, <span class="math inline">\(\varepsilon_{i} \sim N(0,\sigma^{2})\)</span>.</p>
<p>A partir de (a) se tiene que:
<span class="math display">\[
E(Y|X=x_i) = \beta_{0} + \beta_{1}x_i.
\]</span>
Entonces, para <span class="math inline">\(x=0\)</span>, el valor esperado de <span class="math inline">\(Y\)</span> es igual a <span class="math inline">\(\beta_0\)</span>. Cuando <span class="math inline">\(X\)</span> incrementa en una unidad (de <span class="math inline">\(x\)</span> a <span class="math inline">\(x+1\)</span>), el valor esperado de <span class="math inline">\(Y\)</span> incrementa en:
<span class="math display">\[
E(Y|X=x+1) - E(Y|X=x) = \beta_{0} + \beta_{1}(x+1) - (\beta_{0} + \beta_{1}x) = \beta_{1}.
\]</span>
Lo que indica que <span class="math inline">\(\beta_{1}\)</span> representa el cambio en el valor esperado de <span class="math inline">\(Y\)</span> por un cambio unitario en <span class="math inline">\(X\)</span>.</p>
<p>Dado (b), tenemos que <span class="math inline">\(V(Y|X=x_{i}) = \sigma^{2}\)</span>. Es decir que para cualquier valor de <span class="math inline">\(x\)</span>, la varianza de <span class="math inline">\(Y\)</span> es la misma (homocedasticidad). Puesto que los errores están incorrelacionados (c), entonces las observaciones de <span class="math inline">\(Y\)</span> también lo están.</p>
<p>Debido a (d), tenemos que la variable respuesta se distribuye de forma normal. Específicamente, tenemos que: <span class="math inline">\(y_{i} \sim N(\beta_{0} + \beta_{1}x_i, \sigma^{2})\)</span>.</p>
<p>El proceso de generación de datos del modelo de regresión lineal se ilustra en la Figura <a href="modelo-lineal-simple.html#fig:gendataFigure">1.2</a>. El valor esperado de <span class="math inline">\(Y|X\)</span> está representado por la linea negra. Tenemos que, cada observación de <span class="math inline">\(y\)</span> (puntos negros) es una realización de la distribución de <span class="math inline">\(Y|X=x_{i} \sim N(\beta_{0}+\beta_{1}x_{i},\sigma^{2})\)</span> (curvas rojas). En esté ejemplo, suponemos que <span class="math inline">\(\beta_{0}=0\)</span>, <span class="math inline">\(\beta_{1}=1\)</span>, y <span class="math inline">\(\sigma=0.1\)</span>.</p>
<div class="figure" style="text-align: center"><span id="fig:gendataFigure"></span>
<img src="bookdownproj_files/figure-html/gendataFigure-1.png" alt="Proceso generador datos del modelo lineal simple." width="576" />
<p class="caption">
Figure 1.2: Proceso generador datos del modelo lineal simple.
</p>
</div>
</div>
<div id="estimación-de-los-parámetros" class="section level2" number="1.3">
<h2><span class="header-section-number">1.3</span> Estimación de los parámetros</h2>
<p>Los parámetros <span class="math inline">\(\beta_{0}\)</span> y <span class="math inline">\(\beta_{1}\)</span> son desconocidos y deben estimarse a partir de los datos. Para esto utilizamos el método de <strong>mínimos cuadrados ordinarios (MCO)</strong>.</p>
<p>La función objetivo es la siguiente:
<span class="math display" id="eq:rss">\[\begin{equation}
S(\beta_{0},\beta_{1}) = \sum_{i=1}^{n} \left( y_{i} - \beta_{0} - \beta_{1}x_{i} \right)^{2} = \sum_{i=1}^{n} e_{i}^{2}.
 \tag{1.1}
\end{equation}\]</span>
Entonces, tenemos que encontrar la combinación de <span class="math inline">\(\beta_{0}\)</span> y <span class="math inline">\(\beta_{1}\)</span> que minimizan <a href="modelo-lineal-simple.html#eq:rss">(1.1)</a>. Para esto, primero debemos derivar <span class="math inline">\(S(\beta_{0},\beta_{1})\)</span> con respecto a <span class="math inline">\(\beta_{0}\)</span> y <span class="math inline">\(\beta_{1}\)</span>, e igualar estas ecuación a cero. De esta forma obtenemos las <strong>ecuaciones normales</strong>:
<span class="math display" id="eq:normeq1">\[\begin{equation}
\frac{\partial S(\beta_{0},\beta_{1})}{\partial \beta_{0}} = - \frac{2}{n}\sum_{i=1}^{n}\left(y_{i}-\beta_{0}-\beta_{1}x_{i} \right),
\tag{1.2}
\end{equation}\]</span>
y
<span class="math display" id="eq:normeq2">\[\begin{equation}
\frac{\partial S(\beta_{0},\beta_{1})}{\partial \beta_{1}} = - \frac{2}{n}\sum_{i=1}^{n}\left(y_{i}-\beta_{0}-\beta_{1}x_{i} \right)x_{i}.
\tag{1.3}
\end{equation}\]</span></p>
<p>Los estimadores por MCO (<span class="math inline">\(\widehat{\beta}_{0}\)</span> y <span class="math inline">\(\widehat{\beta}_{1}\)</span>) se obtienen resolviendo el sistema de ecuaciones <a href="modelo-lineal-simple.html#eq:normeq1">(1.2)</a> y <a href="modelo-lineal-simple.html#eq:normeq2">(1.3)</a>:
<span class="math display">\[
\widehat{\beta}_{0} = \bar{y} - \widehat{\beta}_{1}\bar{x},
\]</span>
y
<span class="math display">\[
\widehat{\beta}_{1} = \frac{\sum_{i=1}^{n}(x_{i}-\bar{x})(y_{i}-\bar{y})}{\sum_{i=1}^{n}(x_{i}-\bar{x})^2} = \frac{S_{xy}}{S_{xx}} =  cor(X,Y)\frac{s_{Y}}{s_{X}},
\]</span>
donde <span class="math inline">\(s_{X}\)</span> y <span class="math inline">\(s_{Y}\)</span> son las desviaciones estándar muestrales de <span class="math inline">\(X\)</span> y <span class="math inline">\(Y\)</span>.</p>
<p>La diferencia entre el valor observado <span class="math inline">\((y_{i})\)</span> y el valor ajustado correspondiente <span class="math inline">\((\widehat{y}_{i})\)</span> es llamado <strong>residuo</strong> (o residual):
<span class="math display">\[
e_{i}= y_{i} - (\widehat{\beta}_{0} + \widehat{\beta}_{1}x_{i}) = y_{i}-\widehat{y}_{i}, \mbox{ para }i=1,\ldots,n.
\]</span>
La Figura <a href="modelo-lineal-simple.html#fig:Figresiduos">1.3</a> presenta los residuos de forma gráfica. Estos juegan un papel importante para la evaluar la bondad del ajuste del modelo (detectar posibles desviaciones a los supuestos asumidos).</p>
<div class="figure" style="text-align: center"><span id="fig:Figresiduos"></span>
<img src="bookdownproj_files/figure-html/Figresiduos-1.png" alt="Diagrama gráfico de un ajuste por MCO. La recta representa la estimación por MCO, y las lineas discontinuas verticales entre los puntos observados y la recta estimada son los residuos." width="480" />
<p class="caption">
Figure 1.3: Diagrama gráfico de un ajuste por MCO. La recta representa la estimación por MCO, y las lineas discontinuas verticales entre los puntos observados y la recta estimada son los residuos.
</p>
</div>
</div>
<div id="estimación-de-sigma2" class="section level2" number="1.4">
<h2><span class="header-section-number">1.4</span> Estimación de <span class="math inline">\(\sigma^{2}\)</span></h2>
<p>La estimación de <span class="math inline">\(\sigma^{2}\)</span> se hace a partir de la suma de cuadrados de los residuos:
<span class="math display">\[
SS_{res} = \sum_{i=1}^{n}e^{2}_{i} = \sum_{i=1}^{n} (y_{i}-\widehat{\beta}_{0} - \widehat{\beta}_{1}x_{i})^{2}.
\]</span>
El valor esperado de <span class="math inline">\(SS_{res}\)</span> es <span class="math inline">\(E(SS_{res})=(n-2)\sigma^{2}\)</span> (Para el caso de regresión múltiple, ver Sección C.3 de <span class="citation"><a href="#ref-montgomery_introduction_2012" role="doc-biblioref">Montgomery, Peck, and Vining</a> (<a href="#ref-montgomery_introduction_2012" role="doc-biblioref">2012</a>)</span>). Por lo tanto, un estimador insesgado de <span class="math inline">\(\sigma^{2}\)</span> es:
<span class="math display">\[
\widehat{\sigma}_{i} = \frac{SS_{res}}{n-2} = MS_{res}.
\]</span>
La cantidad <span class="math inline">\(MS_{res}\)</span> es llamada <strong>cuadrado medio de los residuos</strong>.</p>
<div id="datos-de-peso-al-nacer.-modelo-y-estimación-de-parametros" class="section level3 unnumbered">
<h3>Datos de peso al nacer. Modelo y estimación de parametros</h3>
<p>Para los datos de peso al nacer se propone el siguiente modelo:
<span class="math display" id="eq:modBirthweight">\[\begin{equation}
\mbox{weight}_{i}= \beta_{0} + \beta_{1}\mbox{age}_{i} + \varepsilon_{i},
\tag{1.4}
\end{equation}\]</span>
donde <span class="math inline">\(\varepsilon_{i} \sim N(0,\sigma^{2})\)</span>.</p>
<p>En R, la estimación por MCO se realiza a través de la función <code>lm</code>:</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="modelo-lineal-simple.html#cb2-1" aria-hidden="true" tabindex="-1"></a>mod <span class="ot">=</span> <span class="fu">lm</span>(weight<span class="sc">~</span>age, <span class="at">data=</span>birthweight)</span>
<span id="cb2-2"><a href="modelo-lineal-simple.html#cb2-2" aria-hidden="true" tabindex="-1"></a>mod</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = weight ~ age, data = birthweight)
## 
## Coefficients:
## (Intercept)          age  
##     -3.6312       0.1752</code></pre>
<p>De aquí obtenemos que <span class="math inline">\(\widehat{\beta}_{0} =-3.63\)</span> y <span class="math inline">\(\widehat{\beta}_{1} =0.18\)</span>. Note que la estimación del intercepto es negativa, lo que es físicamente imposible. Además tampoco tiene sentido una edad gestacional igual a cero. Por lo cual, este parámetro no tiene interpretación en este caso. <span class="math inline">\(\beta_{0}\)</span> solo tiene interpretación cuando las observaciones de <span class="math inline">\(x\)</span> están alrededor de cero.</p>
<p>A partir de <span class="math inline">\(\widehat{\beta}_{1}\)</span>, podemos concluir que la edad gestacional tiene un efecto positivo sobre el peso del recién nacido (el coeficiente estimado es positivo). Por cada incremento de una semana en la edad gestacional, el valor esperado del peso del recién nacido aumenta 0.18 kilogramos.</p>
<p>La representación gráfica del modelo estimado se presenta en la Figura <a href="modelo-lineal-simple.html#fig:FigMCO2">1.4</a>.</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="modelo-lineal-simple.html#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(weight<span class="sc">~</span>age,<span class="at">data=</span>birthweight,<span class="at">pch=</span><span class="dv">20</span>,<span class="at">xlab=</span><span class="st">&quot;edad gestacional(semanas)&quot;</span>,</span>
<span id="cb4-2"><a href="modelo-lineal-simple.html#cb4-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab=</span><span class="st">&#39;peso(kilogramos)&#39;</span>)</span>
<span id="cb4-3"><a href="modelo-lineal-simple.html#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(mod,<span class="at">lwd=</span><span class="dv">2</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:FigMCO2"></span>
<img src="bookdownproj_files/figure-html/FigMCO2-1.png" alt="Gráfico de dispersion del peso del recien nacido y la edad gestacional. La linea representa la estimación por MCO." width="384" />
<p class="caption">
Figure 1.4: Gráfico de dispersion del peso del recien nacido y la edad gestacional. La linea representa la estimación por MCO.
</p>
</div>
<p>La estimación de <span class="math inline">\(\sigma\)</span> es:</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="modelo-lineal-simple.html#cb5-1" aria-hidden="true" tabindex="-1"></a> <span class="fu">sqrt</span>(<span class="fu">sum</span>(mod<span class="sc">$</span>residuals<span class="sc">^</span><span class="dv">2</span>)<span class="sc">/</span><span class="dv">22</span>)</span></code></pre></div>
<pre><code>## [1] 0.5901017</code></pre>
</div>
</div>
<div id="propiedades-de-los-estimadores-por-mco" class="section level2" number="1.5">
<h2><span class="header-section-number">1.5</span> Propiedades de los estimadores por MCO</h2>
<p>Los estimadores de <span class="math inline">\(\widehat{\beta}_{0}\)</span> y <span class="math inline">\(\widehat{\beta}_{1}\)</span> son una combinación lineal de las observaciones:
<span class="math display" id="eq:beta1cl">\[\begin{equation}
\widehat{\beta}_{i} = \sum_{i=1}^{n} \frac{(x_{i}-\bar{x})(y_{i}-\bar{y})}{\sum_{i=1}^{n}(x_{i}-\bar{x})^2} = \sum_{i=1}^{n} \frac{(x_{i}-\bar{x})}{\sum_{i=1}^{n}(x_{i}-\bar{x})^2}y_{i} = \sum_{i=1}^{n}c_{i}y_{i}.
\tag{1.5}
\end{equation}\]</span>
y
<span class="math display">\[
\widehat{\beta}_{0} = \bar{y} - \widehat{\beta}_{1}\bar{x} = \sum_{i=1}^{n}\left( \frac{1}{n} - c_{i}\bar{x} \right)y_{i} = \sum_{i=1}^{n}d_{i}y_{i}.
\]</span>
Además, se tiene que <span class="math inline">\(\sum_{i=1}^{n}c_{i}=0\)</span> y <span class="math inline">\(\sum_{i=1}^{n}c_{i}x_{i}=1\)</span>. Los valores ajustados también son combinaciones lineales de los datos:
<span class="math display">\[
\widehat{y}_{i} = \widehat{\beta}_{0} + \widehat{\beta}_{1}x_{i} = \sum_{i=1}^{n}(d_{i}+c_{i}x_{i})y_{i}.
\]</span>
Puesto que los estimadores de <span class="math inline">\(\beta_{0}\)</span> y <span class="math inline">\(\beta_{1}\)</span> dependen de los errores, estos también son variables aleatorias. Por lo tanto debemos calcular el valor esperado y varianza de <span class="math inline">\(\widehat{\beta}_{0}\)</span> y <span class="math inline">\(\widehat{\beta}_{1}\)</span>.</p>
<p>Si los supuestos del modelo se cumplen, tenemos que el valor esperado de <span class="math inline">\(\widehat{\beta}_{1}\)</span> es:
<span class="math display">\[\begin{equation}
\begin{split}
E(\widehat{\beta}_{1}) &amp;= E\left( \sum_{i=1}^{n}c_{i}y_{i} \right) = \sum_{i=1}^{n}c_{i}E(y_{i}) = \sum_{i=1}^{n} c_{i}(\beta_{0} + \beta_{1}x_{i} + \varepsilon_{i}) \\
&amp;=\beta_{0}\sum_{i=1}^{n}c_{i} + \beta_{1}\sum_{i=1}^{n}c_{i}x_{i} = \beta_{1}.
\end{split}
\nonumber
\end{equation}\]</span>
El valor esperado de <span class="math inline">\(\widehat{\beta}_{0}\)</span> es:
<span class="math display">\[\begin{equation}
\begin{split}
E(\widehat{\beta}_{0}) &amp;= E\left(\bar{y} - \widehat{\beta}_{1}\bar{x} \right) = \frac{1}{n}\sum_{i=1}^{n}E(y_{i}) - \beta_{1}\bar{x} \\
&amp;= \frac{1}{n}\sum_{i=1}^{n}\left(\beta_{0} + \beta_{1}x_{i}\right) - \beta_{1}\bar{x} = \beta_{0}.
\end{split}
\nonumber
\end{equation}\]</span></p>
<p>Es decir que <span class="math inline">\(\widehat{\beta}_{0}\)</span> y <span class="math inline">\(\widehat{\beta}_{1}\)</span> son estimadores insesgado de <span class="math inline">\(\beta_{0}\)</span> y <span class="math inline">\(\beta_{1}\)</span>,respectivamente.</p>
<p>La varianza de <span class="math inline">\(\widehat{\beta}_{1}\)</span> y <span class="math inline">\(\widehat{\beta}_{0}\)</span> son:
<span class="math display">\[
V(\widehat{\beta}_{1})= V \left( \sum_{i=1}^{n}c_{i}y_{i}\right) = \sum_{i=1}^{n}c_{i}^{2}V(y_{i}) = \sigma^{2}\sum_{i=1}^{n}c_{i}^{2} = \frac{\sigma^{2}}{S_{xx}},
\]</span>
y
<span class="math display">\[\begin{equation}
\begin{split}
V(\widehat{\beta}_{0}) &amp;= V \left( \bar{y} - \widehat{\beta}_{1}\bar{x}\right) = V (\bar{y}) + \bar{x}^{2}V(\widehat{\beta}_{1}) - 2\bar{x}Cov(\bar{y},\widehat{\beta}_{1}) \\
&amp;= \sigma^{2} \left(\frac{1}{n} + \frac{\bar{x}^{2}}{S_{xx}}. \right),
\end{split}
\nonumber
\end{equation}\]</span>
respectivamente. Finalmente, la covarianza entre <span class="math inline">\(\widehat{\beta}_{0}\)</span> y <span class="math inline">\(\widehat{\beta}_{1}\)</span> es:
<span class="math display">\[\begin{equation}
\begin{split}
Cov(\widehat{\beta}_{0},\widehat{\beta}_{1}) &amp;= Cov\left(\bar{y} - \widehat{\beta}_{1}\bar{x}, \widehat{\beta}_{1} \right) = Cov\left( \bar{y}, \widehat{\beta}_{1}\right) - \bar{x}V\left(\widehat{\beta}_{1}\right) \\
&amp;=  - \sigma^{2}\frac{\bar{x}}{S_{xx}}.
\end{split}
\nonumber
\end{equation}\]</span></p>
<p>Si se cumple que <span class="math inline">\(E(\varepsilon_{i}) = 0\)</span>, <span class="math inline">\(V(\varepsilon_{i}) = \sigma^{2}\)</span> y <span class="math inline">\(Cov(\varepsilon_{i},\varepsilon_{j})=0\)</span>, se puede probar que los estimadores por MCO son insesgado y de varianza mínima (<strong>teorema de Gauss-Markov</strong>). Para la demostración en el caso de regresión múltiple, ver Sección C4 de <span class="citation"><a href="#ref-montgomery_introduction_2012" role="doc-biblioref">Montgomery, Peck, and Vining</a> (<a href="#ref-montgomery_introduction_2012" role="doc-biblioref">2012</a>)</span>. Esto quiere decir que, comparado con todos los posibles estimadores insesgados que son combinación lineal de las observaciones, <span class="math inline">\(\widehat{\beta}_{0}\)</span> y <span class="math inline">\(\widehat{\beta}_{1}\)</span> tienen las varianzas más pequeñas. Por esto los estimadores por MCO son considerados los <strong>mejores estimadores lineales insesgados</strong>.</p>
</div>
<div id="inferencia" class="section level2" number="1.6">
<h2><span class="header-section-number">1.6</span> Inferencia</h2>
<p>También podemos hacer pruebas de hipótesis e intervalos de confianza para los parámetros del modelo y/o pronósticos.</p>
<p>Por ejemplo, en los datos del peso al nacer podemos estar interesados en evaluar si la edad gestacional tiene un efecto positivo sobre el peso al nacer. Por lo tanto, debemos probar si <span class="math inline">\(\beta_{1} &gt; 0\)</span>. También podríamos estar interesados en el valor esperado de un recién nacido para cierto valor especifico de edad gestacional, por ejemplo 38 semanas. Entonces, podemos calcular un intervalo de confianza para <span class="math inline">\(E(Y|x=38)\)</span>.</p>
<div id="pruebas-de-hipótesis" class="section level3" number="1.6.1">
<h3><span class="header-section-number">1.6.1</span> Pruebas de hipótesis</h3>
<p>Suponga la siguiente hipótesis:
<span class="math display" id="eq:H0beta1">\[\begin{equation}
H_{0}: \beta_{1} = \beta_{10} \mbox{  } H_{1}: \beta_{1} \neq \beta_{10}.
\tag{1.6}
\end{equation}\]</span>
Dado que <span class="math inline">\(\widehat{\beta}_{1}\)</span> es una combinación lineal de <span class="math inline">\(y_{i}\)</span> <a href="modelo-lineal-simple.html#eq:beta1cl">(1.5)</a>, podemos concluir que:
<span class="math display">\[
\widehat{\beta}_{1} \sim N\left(\beta_{1}, \frac{\sigma^{2}}{S_{xx}}\right).
\]</span>
Además,
<span class="math display" id="eq:distB1">\[\begin{equation}
t_{0} = \frac{\widehat{\beta}_{1}-\beta_{10}}{\sqrt{\frac{MS_{res}}{S_{xx}}}}\sim t_{n-2}.
\tag{1.7}
\end{equation}\]</span>
Por lo tanto, <span class="math inline">\(t_{0}\)</span> es el estadístico de prueba para las hipótesis <a href="modelo-lineal-simple.html#eq:H0beta1">(1.6)</a>. Entonces, rechazamos <span class="math inline">\(H_{0}\)</span> si <span class="math inline">\(|t_{0}| \ge t_{1-\alpha/2,n-p}\)</span> (o por medio del valor-<span class="math inline">\(p\)</span> asociado).</p>
<p>De igual forma, para evaluar:
<span class="math display">\[
H_{0}: \beta_{0} = \beta_{00} \mbox{  } H_{1}: \beta_{0} \neq \beta_{00},
\]</span>
el estadístico de prueba es:
<span class="math display" id="eq:distB0">\[\begin{equation}
t_{0} = \frac{\widehat{\beta}_{0}-\beta_{00}}{\sqrt{MS_{res}\left(\frac{1}{n}+\frac{\bar{x}^{2}}{S_{xx}} \right)}} \sim t_{n-2}.
 \tag{1.8}
\end{equation}\]</span></p>
</div>
<div id="análisis-de-varianza" class="section level3" number="1.6.2">
<h3><span class="header-section-number">1.6.2</span> Análisis de varianza</h3>
El análisis de varianza se basa en la partición de la variabilidad total de la variable respuesta <span class="math inline">\(y\)</span> en dos componentes, uno debido al modelo ajustado y otro al error. Primero, empecemos con la siguiente identidad:
<span class="math display" id="eq:decomposion">\[\begin{equation}
y_{i} - \bar{y} = (y_{i} - \widehat{y}_{i}) + (\widehat{y}_{i} - \bar{y}).
\tag{1.9}
\end{equation}\]</span>
La Figura <a href="modelo-lineal-simple.html#fig:anovafig">1.5</a> muestra la partición <a href="modelo-lineal-simple.html#eq:decomposion">(1.9)</a> en el punto <span class="math inline">\(i=3\)</span>. Aquí vemos que una parte de la diferencia entre <span class="math inline">\(y_{3}\)</span> y <span class="math inline">\(\bar{y}\)</span> es explicada por el modelo (línea discontinua roja).
<div class="figure" style="text-align: center"><span id="fig:anovafig"></span>
<img src="bookdownproj_files/figure-html/anovafig-1.png" alt="Representación gráfica de la partición \@ref(eq:decomposion)." width="576" />
<p class="caption">
Figure 1.5: Representación gráfica de la partición <a href="modelo-lineal-simple.html#eq:decomposion">(1.9)</a>.
</p>
</div>
<p>Ahora evelavamos al cuadrado <a href="modelo-lineal-simple.html#eq:decomposion">(1.9)</a> y sumamos todos los componentes:
<span class="math display" id="eq:ss">\[\begin{equation}
\begin{split}
\sum_{i=1}^{n} (y_{i} - \bar{y})^{2} &amp;= \sum_{i=1}^{n} (y_{i} - \widehat{y}_{i})^{2} + \sum_{i=1}^{n}(\widehat{y}_{i} - \bar{y})^{2} + 2 \sum_{i=1}^{n}(y_{i} - \widehat{y}_{i})(\widehat{y}_{i} - \bar{y}) \\
&amp;= \sum_{i=1}^{n} (y_{i} - \widehat{y}_{i})^{2} + \sum_{i=1}^{n}(\widehat{y}_{i} - \bar{y})^{2} \\
SST &amp;= SS_{R} + SS_{res},
\end{split}
\tag{1.10}
\end{equation}\]</span>
donde <span class="math inline">\(SST\)</span> es llamada la <strong>suma de cuadrados totales</strong> (con <span class="math inline">\(n-1\)</span> grados de libertad), <span class="math inline">\(SS_{R}\)</span> es la <strong>suma de cuadrados de la regresión</strong> (con <span class="math inline">\(1\)</span> grados de libertad), y <span class="math inline">\(SS_{res}\)</span> es la <strong>suma de cuadrados residual o del error</strong> (con <span class="math inline">\(n-2\)</span> grados de libertad).</p>
<p>El análisis de varianza nos permite evaluar la siguiente hipótesis:
<span class="math display" id="eq:anova">\[\begin{equation}
H_{0}: \beta_{1} = 0 \mbox{  }H_{1}:  \beta_{1} \neq 0.
\tag{1.11}
\end{equation}\]</span></p>
<p>Se puede demostrar que si <span class="math inline">\(H_{0}\)</span> es cierta:
<span class="math display">\[
SS_{res} = \frac{(n-2)MS_{res}}{\sigma^{2}} \sim \chi^{2}_{n-2} \mbox{,} \ \  \frac{SS_{R}}{\sigma^{2}} \sim \chi^{2}_{1},
\]</span>
y que <span class="math inline">\(SS_{res}\)</span> y <span class="math inline">\(SS_{R}\)</span> son independientes. Por lo tanto:
<span class="math display">\[
F_{0} = \frac{SS_{R}/1}{SS_{res}/(n-2)} = \frac{MS_{R}}{MS_{res}} \sim F_{(1,n-2)}.
\]</span>
Además, <span class="math inline">\(E(MS_{res})=\sigma^{2}\)</span> y <span class="math inline">\(E(MS_{res})=\sigma^{2} + \beta_{1}^{2}S_{xx}\)</span>.</p>
<p>Entonces, podemos utilizar <span class="math inline">\(F_{0}\)</span> como estadístico de prueba de <a href="modelo-lineal-simple.html#eq:anova">(1.11)</a>. Rechazamos <span class="math inline">\(H_{0}\)</span> si <span class="math inline">\(F_{0} &gt; F_{\alpha,1,n-2}\)</span>.</p>
<p>Si <span class="math inline">\(H_{0}\)</span> es falsa, <span class="math inline">\(F_{0}\)</span> sigue una distribución F no central con <span class="math inline">\(1\)</span> y <span class="math inline">\(n-2\)</span> grados de libertad, y parámetro de no centralidad igual a <span class="math inline">\(\lambda=(\beta_{1}^{2}S_{xx})/\sigma^{2}\)</span>.</p>
<p>Estos resultados se pueden resumir en la Tabla <a href="modelo-lineal-simple.html#tab:tableAnova">1.1</a>.</p>
<table>
<caption><span id="tab:tableAnova">Table 1.1: </span> Tabla de ANOVA</caption>
<thead>
<tr class="header">
<th align="right">Fuente de variación</th>
<th align="right">g.l.</th>
<th align="right">SS</th>
<th align="right">MS</th>
<th align="right"><span class="math inline">\(F\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">regresión</td>
<td align="right">1</td>
<td align="right"><span class="math inline">\(SS_{R}\)</span></td>
<td align="right"><span class="math inline">\(MS_{R}\)</span></td>
<td align="right"><span class="math inline">\(F_{0}\)</span></td>
</tr>
<tr class="even">
<td align="right">residuos</td>
<td align="right">n-2</td>
<td align="right"><span class="math inline">\(SS_{res}\)</span></td>
<td align="right"><span class="math inline">\(MS_{res}\)</span></td>
<td align="right"></td>
</tr>
<tr class="odd">
<td align="right">Total</td>
<td align="right">n-1</td>
<td align="right"><span class="math inline">\(SST\)</span></td>
<td align="right"></td>
<td align="right"></td>
</tr>
</tbody>
</table>
<p>La cantidad:
<span class="math display">\[
R^{2} = \frac{SS_{R}}{SS_{res}} = 1 - \frac{SS_{res}}{SST},
\]</span>
es llamada <strong>coeficiente de determinación</strong>, y cuantifica la cantidad de variabilidad de <span class="math inline">\(y\)</span> que es explicada por <span class="math inline">\(x\)</span>. Dado que <span class="math inline">\(0 \leq SS_{res} \leq SST\)</span>, se tiene que <span class="math inline">\(0 \leq R^{2} \leq 1\)</span>. Por lo tanto, valores cercanos a <span class="math inline">\(1\)</span> implican que el modelo explica gran parte de la variabilidad de <span class="math inline">\(y\)</span>.</p>
</div>
<div id="datos-de-peso-al-nacer.-pruebas-de-hipótesis-y-anova" class="section level3 unnumbered">
<h3>Datos de peso al nacer. Pruebas de hipótesis y ANOVA</h3>
<p>Se quiere probar que la edad gestacional tiene influencia sobre el peso al nacer del recién nacido. Esto es:
<span class="math display">\[
H_{0}: \beta_{1} = 0 \qquad H_{1}: \beta_{1} \neq 0. 
\]</span>
Tanto la prueba de hipótesis basada en <span class="math inline">\(t_{0}\)</span>, el valor <span class="math inline">\(F_{0}\)</span> del ANOVA, y el <span class="math inline">\(R^{2}\)</span> se pueden observar usando la función <code>summary</code>:</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="modelo-lineal-simple.html#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = weight ~ age, data = birthweight)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.71314 -0.36708  0.01982  0.26741  0.93034 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -3.63119    1.01556  -3.576 0.000932 ***
## age          0.17525    0.02586   6.778 3.83e-08 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.4376 on 40 degrees of freedom
## Multiple R-squared:  0.5346, Adjusted R-squared:  0.5229 
## F-statistic: 45.94 on 1 and 40 DF,  p-value: 3.828e-08</code></pre>
<p>Del resultado anterior, tenemos que:</p>
<ul>
<li><span class="math inline">\(t_{0}=6.778\)</span> con un valor-<span class="math inline">\(p\)</span> asociado de 0. Por lo tanto, rechazamos <span class="math inline">\(H_{0}\)</span> y concluimos que la edad gestacional tiene un efecto significativo sobre el peso al nacer.</li>
<li>La función <code>summary</code> no arroja como resultado una tabla ANOVA. Pero podemos observar el valor <span class="math inline">\(F_{0} = 45.94\)</span> con un valor <span class="math inline">\(p\)</span> asociado de 0.</li>
<li><span class="math inline">\(R^{2} = 0.535\)</span>, lo que indica que el 53.5% de la variabilidad del peso al nacer es explicada por la edad gestacional.</li>
</ul>
</div>
<div id="intervalos-de-confianza" class="section level3" number="1.6.3">
<h3><span class="header-section-number">1.6.3</span> Intervalos de confianza</h3>
<div id="intervalos-de-confianza-para-beta_0-beta_1-y-sigma2" class="section level4 unnumbered">
<h4>Intervalos de confianza para <span class="math inline">\(\beta_{0}\)</span>, <span class="math inline">\(\beta_{1}\)</span> y <span class="math inline">\(\sigma^{2}\)</span></h4>
<p>Los intervalos de confianza para <span class="math inline">\(\beta_{0}\)</span> y <span class="math inline">\(\beta_{1}\)</span> se construyen a partir de las distribuciones de probabilidad de <span class="math inline">\(\widehat{\beta}_{0}\)</span> y <span class="math inline">\(\widehat{\beta}_{1}\)</span>. Esto es, <a href="modelo-lineal-simple.html#eq:distB0">(1.8)</a> y <a href="modelo-lineal-simple.html#eq:distB1">(1.7)</a>, respectivamente.</p>
<p>Por lo tanto, el intervalo del <span class="math inline">\(100(1-\alpha)\%\)</span> de confianza para <span class="math inline">\(\beta_{j}\)</span> es:
<span class="math display">\[
\widehat{\beta}_{j} \pm t_{1-\alpha/2,n-2}\sqrt{V(\widehat{\beta}_{j})}, \mbox{ para }j=0,1.
\]</span>
Se puede demostrar que <span class="math inline">\((n-2)MS_{res}/\sigma^{2}\sim \chi^{2}_{n-2}\)</span>. Por lo tanto:
<span class="math display">\[
P \left\{ \chi^{2}_{\alpha/2,n-2} \leq (n-2)MS_{res}/\sigma^{2} \leq \chi^{2}_{1-\alpha/2,n-2} \right\} = 1-\alpha.
\]</span>
Entonces, el intervalo del <span class="math inline">\(100(1-\alpha)\%\)</span> de confianza para <span class="math inline">\(\sigma^{2}\)</span> es:
<span class="math display">\[
\left\{ \frac{(n-2)MS_{res}}{\chi^{2}_{1-\alpha/2,n-2}}; \frac{(n-2)MS_{res}}{\chi^{2}_{\alpha/2,n-2}} \right\}.
\]</span></p>
</div>
<div id="intervalos-de-confianza-para-ey_i-y-una-predicción-futura" class="section level4 unnumbered">
<h4>Intervalos de confianza para <span class="math inline">\(E(y_{i})\)</span> y una predicción futura</h4>
<p>Cuando el objetivo de ajustar un modelo de regresión es hacer predicciones, es posible hacer intervalos de confianza para la respuesta media, esto es <span class="math inline">\(E(Y|x_{0})=\mu_{Y|x_{0}}\)</span>, donde <span class="math inline">\(x_{0}\)</span> es un valor de la covariable dentro del rango de valores observados de <span class="math inline">\(x\)</span> en los datos.</p>
<p>Una estimación insesgada de <span class="math inline">\(\mu_{Y|x_{0}}\)</span> es:
<span class="math display">\[
\widehat{\mu}_{Y|x_{0}} = \widehat{\beta}_{0} + \widehat{\beta}_{1}x_{0}.
\]</span>
La varianza de <span class="math inline">\(\widehat{\mu}_{Y|x_{0}}\)</span> es:
<span class="math display">\[\begin{equation}
\begin{split}
V(\widehat{\mu}_{Y|x_{0}}) &amp;= V(\widehat{\beta}_{0} + \widehat{\beta}_{1}x_{0}) = V(\widehat{\beta}_{0}) + x_{0}^{2}V(\widehat{\beta}_{1}) + 2x_{0}Cov(\widehat{\beta}_{0},\widehat{\beta}_{1}) \\
&amp;= \sigma^{2}\left(\frac{1}{n} + \frac{\bar{x}^{2}}{S_{xx}} \right) + \sigma^{2}x_{0}^{2}\frac{1}{S_{xx}} - 2\sigma^{2}x_{0}\frac{\bar{x}}{S_{xx}} \\
&amp;= \sigma^{2}\left[\frac{1}{n} + \frac{(x_{0}-\bar{x})^{2}}{S_{xx}} \right].
\end{split}
\nonumber
\end{equation}\]</span>
El intervalo de confianza se construye a partir de la siguiente distribución muestral:
<span class="math display">\[
\frac{\widehat{\mu}_{Y|x_{0}} - E(Y|x_{0})}{\sqrt{MS_{res}[1/n+(x_{0}-\bar{x})^{2}/S_{xx}]}} \sim t_{n-2}.
\]</span>
Por lo tanto, el intervalo del <span class="math inline">\(100(1-\alpha)\%\)</span> de confianza para <span class="math inline">\(\mu_{Y|x_{0}}\)</span> es:
<span class="math display">\[\begin{equation}
\widehat{\mu}_{Y|x_{0}} \pm t_{1-\alpha/2,n-2}\sqrt{MS_{res}[1/n+(x_{0}-\bar{x})^{2}/S_{xx}]}.
\label{eq:CImean}
\end{equation}\]</span>
Note que la longitud del intervalo de confianza de <span class="math inline">\(\widehat{\mu}_{Y|x_{0}}\)</span> depende del punto <span class="math inline">\(x_{0}\)</span>. La menor longitud se obtiene en el punto <span class="math inline">\(x_{0}=\bar{x}\)</span>, y el intervalo es cada vez mas ancho a medida que nos alejamos de ese punto.</p>
<p>Ahora consideremos hacer una predicción de una observación futura de <span class="math inline">\(y\)</span> para cierto valor de <span class="math inline">\(x\)</span>. Si queremos hacer la predicción para <span class="math inline">\(x=x_{0}\)</span>, entonces la predicción de la nueva observación es:
<span class="math display">\[
\widetilde{y}_{0} = \widehat{\beta}_{0} + \widehat{\beta}_{1}x_{0}.
\]</span>
Asumiendo que el modelo es correcta, el verdadero valor de <span class="math inline">\(y_{0}\)</span> es:
<span class="math display">\[
\widetilde{y}_{0} = \widehat{\beta}_{0} + \widehat{\beta}_{1}x_{0} + \varepsilon_{0}.
\]</span>
y su varianza es:
<span class="math display" id="eq:varpred">\[\begin{equation}
V(\widetilde{y}_{0}) = \sigma^{2}+\sigma^{2}\left[\frac{1}{n} + \frac{(x_{0}-\bar{x})^{2}}{S_{xx}} \right].
\tag{1.12}
\end{equation}\]</span>
El primer término a la derecha de <a href="modelo-lineal-simple.html#eq:varpred">(1.12)</a> corresponde a la variabilidad de <span class="math inline">\(\varepsilon_{0}\)</span> y el segundo al error de estimación de los coeficientes <span class="math inline">\(\beta_{0}\)</span> y <span class="math inline">\(\beta_{1}\)</span>. A partir de estos resultados, el intervalo del <span class="math inline">\(100(1-\alpha)\%\)</span> de predicción de una observación futura en <span class="math inline">\(x=x_{0}\)</span> es:
<span class="math display">\[
\widehat{\mu}_{Y|x_{0}} \pm t_{1-\alpha/2,n-2}\sqrt{MS_{res}[1+1/n+(x_{0}-\bar{x})^{2}/S_{xx}]}.
\]</span></p>
</div>
</div>
<div id="datos-de-peso-al-nacer.-intervalos-de-confianza" class="section level3 unnumbered">
<h3>Datos de peso al nacer. Intervalos de confianza</h3>
<p>El intervalo del 95% de confianza para los parámetros del modelo <a href="modelo-lineal-simple.html#eq:modBirthweight">(1.4)</a> son:</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="modelo-lineal-simple.html#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(mod)</span></code></pre></div>
<pre><code>##                  2.5 %     97.5 %
## (Intercept) -5.6837190 -1.5786621
## age          0.1229923  0.2275067</code></pre>
<p>Para <span class="math inline">\(\beta_{1}\)</span>, con un nivel de confianza del 95% podemos decir que cuando la edad gestacional aumenta en una unidad, el peso medio del recién nacido aumenta entre 123 y 228 gramos. Como mencionamos antes, <span class="math inline">\(\beta_{0}\)</span> no tiene interpretación en este modelo.</p>
<p>El intervalo del 95% de confianza para <span class="math inline">\(\sigma\)</span> se calcula “a pie” de la siguiente forma:</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="modelo-lineal-simple.html#cb11-1" aria-hidden="true" tabindex="-1"></a>var.limInf <span class="ot">=</span> <span class="fu">sum</span>(mod<span class="sc">$</span>residuals<span class="sc">^</span><span class="dv">2</span>)<span class="sc">/</span><span class="fu">qchisq</span>(<span class="fl">0.975</span>,<span class="at">df=</span>mod<span class="sc">$</span>df.residual)</span>
<span id="cb11-2"><a href="modelo-lineal-simple.html#cb11-2" aria-hidden="true" tabindex="-1"></a>var.limSup <span class="ot">=</span> <span class="fu">sum</span>(mod<span class="sc">$</span>residuals<span class="sc">^</span><span class="dv">2</span>)<span class="sc">/</span><span class="fu">qchisq</span>(<span class="fl">0.025</span>,<span class="at">df=</span>mod<span class="sc">$</span>df.residual)</span>
<span id="cb11-3"><a href="modelo-lineal-simple.html#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="fu">sqrt</span>(<span class="fu">c</span>(var.limInf,var.limSup))</span></code></pre></div>
<pre><code>## [1] 0.3593008 0.5599503</code></pre>
<p>Se quiere predecir el peso medio de los recién nacidos en la semana gestacional 36. La estimación puntual es:
<span class="math display">\[
\widehat{\mu}_{Y|x_{0}=36} = \widehat{\beta}_{0} + \widehat{\beta}_{1}(36) = -3.6312 + 0.1751*36 = 2.672.
\]</span>
El intervalo del 95% de confianza para <span class="math inline">\(\widehat{\mu}_{Y|x_{0}=36}\)</span> se puede calcular de la siguiente forma:</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="modelo-lineal-simple.html#cb13-1" aria-hidden="true" tabindex="-1"></a>x.nuevo <span class="ot">=</span> <span class="fu">data.frame</span>(<span class="at">age=</span><span class="dv">36</span>)</span>
<span id="cb13-2"><a href="modelo-lineal-simple.html#cb13-2" aria-hidden="true" tabindex="-1"></a>pred.media <span class="ot">=</span> <span class="fu">predict</span>(mod,x.nuevo,<span class="at">interval =</span> <span class="st">&#39;confidence&#39;</span>)</span>
<span id="cb13-3"><a href="modelo-lineal-simple.html#cb13-3" aria-hidden="true" tabindex="-1"></a>pred.media</span></code></pre></div>
<pre><code>##        fit     lwr      upr
## 1 2.677792 2.46233 2.893254</code></pre>
<p>Esto quiere decir que, con un nivel de confianza del 95%, el peso medio de los recién nacidos en la semana gestacional 36 está entre 2.46 y 2.89 kilogramos.</p>
<p>Ahora, se quiere predecir el peso de un recién nacido en la semana gestacional 38, para esto calculamos un intervalo de predicción del 95%:</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="modelo-lineal-simple.html#cb15-1" aria-hidden="true" tabindex="-1"></a>x.nuevo <span class="ot">=</span> <span class="fu">data.frame</span>(<span class="at">age=</span><span class="dv">38</span>)</span>
<span id="cb15-2"><a href="modelo-lineal-simple.html#cb15-2" aria-hidden="true" tabindex="-1"></a>pred.nuevaObs <span class="ot">=</span> <span class="fu">predict</span>(mod,x.nuevo,<span class="at">interval =</span> <span class="st">&#39;prediction&#39;</span>)</span>
<span id="cb15-3"><a href="modelo-lineal-simple.html#cb15-3" aria-hidden="true" tabindex="-1"></a>pred.nuevaObs</span></code></pre></div>
<pre><code>##        fit      lwr      upr
## 1 3.028291 2.131178 3.925404</code></pre>
<p>Por lo tanto, con un nivel de confianza del 95% el peso de un recién nacido en la semana gestacional 38 está entre 2.13 y 3.93 kilogramos.</p>
<p>Gráficamente, podemos ver los intervalos de confianza y predicción de la siguiente forma:</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="modelo-lineal-simple.html#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(weight<span class="sc">~</span>age,<span class="at">data=</span>birthweight,<span class="at">pch=</span><span class="dv">20</span>,<span class="at">xlab=</span><span class="st">&quot;Edad gestacional(semanas)&quot;</span>,</span>
<span id="cb17-2"><a href="modelo-lineal-simple.html#cb17-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab=</span><span class="st">&#39;Peso(kilogramos)&#39;</span>)</span>
<span id="cb17-3"><a href="modelo-lineal-simple.html#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(mod)</span>
<span id="cb17-4"><a href="modelo-lineal-simple.html#cb17-4" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(x.nuevo<span class="sc">$</span>age,pred.media[,<span class="dv">2</span>],<span class="at">lty=</span><span class="dv">2</span>)</span>
<span id="cb17-5"><a href="modelo-lineal-simple.html#cb17-5" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(x.nuevo<span class="sc">$</span>age,pred.media[,<span class="dv">3</span>],<span class="at">lty=</span><span class="dv">2</span>)</span>
<span id="cb17-6"><a href="modelo-lineal-simple.html#cb17-6" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(x.nuevo<span class="sc">$</span>age,pred.nuevaObs[,<span class="dv">2</span>],<span class="at">lty=</span><span class="dv">3</span>)</span>
<span id="cb17-7"><a href="modelo-lineal-simple.html#cb17-7" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(x.nuevo<span class="sc">$</span>age,pred.nuevaObs[,<span class="dv">3</span>],<span class="at">lty=</span><span class="dv">3</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:birthweightIC"></span>
<img src="bookdownproj_files/figure-html/birthweightIC-1.png" alt="\label{fig:BWdata2} Intervalos del 95\% de confianza (línea discontinua) y predicción (línea punteada) para el peso del recien nacido en función de la edad gestacional." width="480" />
<p class="caption">
Figure 1.6:  Intervalos del 95% de confianza (línea discontinua) y predicción (línea punteada) para el peso del recien nacido en función de la edad gestacional.
</p>
</div>
</div>
</div>
<div id="estimador-por-máxima-verosimilitud" class="section level2" number="1.7">
<h2><span class="header-section-number">1.7</span> Estimador por máxima verosimilitud</h2>
<p>Si consideramos que <span class="math inline">\(\varepsilon_{i}\sim N(0,\sigma^{2})\)</span>, entonces las observación también se distribuyen de forma normal <span class="math inline">\(y_{i}\sim N(\beta_{0}+\beta_{1}x_{i},\sigma^{2})\)</span>. Si además asumimos que las observaciones <span class="math inline">\((y_{i},x_{i})\)</span> son independientes, entonces la función de verosimilitud es:
<span class="math display">\[\begin{equation}
\begin{split}
L(\boldsymbol{\theta}) =&amp; \prod_{i=1}^{n} \left(\sqrt{2\pi\sigma^{2}} \right)^{-1/2}\exp\left[ - \frac{1}{2\sigma^{2}}(y_{i}-\beta_{0}-\beta_{1}x_{i})^{2} \right] \\
=&amp; \left( \sqrt{2\pi\sigma^{2}} \right)^{-n/2}\exp\left[ - \frac{1}{2\sigma^{2}} \sum_{i=1}^{n}(y_{i}-\beta_{0}-\beta_{1}x_{i})^{2}\right],
\end{split}
\nonumber
\end{equation}\]</span>
para <span class="math inline">\(\boldsymbol{\theta}=(\beta_{0},\beta_{1},\sigma^{2})&#39;\)</span>. La log-verosimilitud es:
<span class="math display">\[
\ell (\boldsymbol{\theta}) = - \left(\frac{n}{2}\right)\left[ \log (2 \pi) - \log \sigma^{2}\right] - \frac{1}{2\sigma^{2}}\sum_{i=1}^{n}(y_{i} - \beta_{0}-\beta_{1}x_{i})^{2}. 
\]</span>
El estimador de máxima verosimilitud de <span class="math inline">\(\boldsymbol{\theta}\)</span> debe satisfacer:
<span class="math display">\[
\left. \frac{\partial \ell(\boldsymbol{\theta})}{\partial \beta_{0}} \right|_{\widetilde{\boldsymbol{\theta}}} = \frac{1}{\widetilde{\sigma}^{2}}\sum_{i=1}^{n}(y_{i} - \beta_{0}-\beta_{1}x_{i}) = 0,
\]</span>
<span class="math display">\[
\left. \frac{\partial \ell(\boldsymbol{\theta})}{\partial \beta_{1}} \right|_{\widetilde{\boldsymbol{\theta}}} = \frac{1}{\widetilde{\sigma}^{2}}\sum_{i=1}^{n}(y_{i} - \beta_{0}-\beta_{1}x_{i})x_{i} = 0,
\]</span>
y
<span class="math display">\[
\left. \frac{\partial \ell(\boldsymbol{\theta})}{\partial \sigma^{2}} \right|_{\widetilde{\boldsymbol{\theta}}} = -\frac{n}{2\widetilde{\sigma}^{2}} + \frac{n}{2\widetilde{\sigma}^{4}}
\sum_{i=1}^{n}(y_{i} - \beta_{0}-\beta_{1}x_{i})^{2} = 0,
\]</span>
Luego de solucionar las ecuaciones anteriores se obtienen los estimadores por máxima verosimilitud:
<span class="math display">\[
\widetilde{\beta}_{0} = \bar{y} - \widetilde{\beta}_{1}\bar{x},
\]</span>
<span class="math display">\[
\widetilde{\beta}_{1} = \frac{\sum_{i=1}^{n}y_{i}(x_{i}-\bar{x})}{\sum_{i=1}^{n}(x_{i}-\bar{x})^{2}},
\]</span>
y
<span class="math display">\[
\widetilde{\sigma}^{2} = \frac{\sum_{i=1}^{n}(y_{i}-\beta_{0}-\beta_{1}x_{i})^{2}}{n}.
\]</span>
Aquí observamos que los estimadores por máxima verosimilitud para <span class="math inline">\(\beta_{0}\)</span> y <span class="math inline">\(\beta_{1}\)</span> son equivalente a los estimadores por MCO. El estimador de <span class="math inline">\(\sigma^{2}\)</span> es sesgado, sin embargo el sesgo disminuye a medida que <span class="math inline">\(n\)</span> crece.</p>
<p>Por lo general, los estimadores por máxima verosimilitud tienen mejores propiedades que los estimadores por MCO. Son asintoticamente insesgados, consistentes y asintoticamente de mínima varianza. Sin embargo, estos requieren de supuestos distribucionales completos. Recordemos que los estimadores por MCO solo requieren de una correcta especificación de los dos primeros momentos (valor esperado, varianza y covarianza).</p>
</div>
<div id="algunas-consideraciones-finales" class="section level2" number="1.8">
<h2><span class="header-section-number">1.8</span> Algunas consideraciones finales</h2>
<ul>
<li>Las conclusiones sobre los modelos de regresión se hacen sobre el rango de valores observados de las covariables (interpolación). Por ejemplo, en los datos de los recién nacidos, se pueden hacer inferencias sobre el peso al nacer para bebés que nacen en entre las semanas 33 y 45. Cuando hacemos predicciones fuera de este rango estaríamos extrapolando.</li>
</ul>
<p>Por extrapolación nos referimos a hacer predicciones fuera del rango observado de <span class="math inline">\(x\)</span>. La Figura <a href="modelo-lineal-simple.html#fig:extrapolacion">1.7</a> muestra el problema que se puede cometer cuando extrapolamos. Si tenemos datos en el rango <span class="math inline">\(x_{min} \leq x \leq x_{max}\)</span>, un modelo lineal es una buena aproximación de <span class="math inline">\(E(Y|x)\)</span>. Pero, esa aproximación no es buena para <span class="math inline">\(x&gt;x_{max}\)</span>. Por lo tanto, se estaría cometiendo errores graves cuando hacemos predicciones de <span class="math inline">\(Y\)</span> para valores de <span class="math inline">\(x\)</span> mayores a <span class="math inline">\(x_{max}\)</span> (por ejemplo en el punto <span class="math inline">\(x_{0}\)</span>).</p>
<div class="figure" style="text-align: center"><span id="fig:extrapolacion"></span>
<img src="bookdownproj_files/figure-html/extrapolacion-1.png" alt="Peligro de extrapolar. La curva negra representa $E(Y|x)$ y la línea roja es el ajuste del modelo lineal con los datos observados de $x$. La predicción en el punto $x_{0}$ es bastante sesgada." width="480" />
<p class="caption">
Figure 1.7: Peligro de extrapolar. La curva negra representa <span class="math inline">\(E(Y|x)\)</span> y la línea roja es el ajuste del modelo lineal con los datos observados de <span class="math inline">\(x\)</span>. La predicción en el punto <span class="math inline">\(x_{0}\)</span> es bastante sesgada.
</p>
</div>
<ul>
<li><p>La posición de los valores de <span class="math inline">\(x\)</span> tienen una influencia sobre el ajuste por MCO. Particularmente, la estimación de <span class="math inline">\(\beta_{1}\)</span> está fuertemente influenciada por los valores alejados de <span class="math inline">\(x\)</span> y <span class="math inline">\(y\)</span>. A estos puntos se les denomina <strong>puntos influyentes</strong>. En la Figura <a href="modelo-lineal-simple.html#fig:influyentes">1.8</a>(a) podemos ver como un solo punto tiene una influencia alta en la estimación de los parámetros del modelo.</p></li>
<li><p>Los <strong>valores atípicos</strong> son observaciones que difieren considerablemente del resto de los datos (generalmente en <span class="math inline">\(y\)</span>). Un punto atípico puede afectar la estimación de <span class="math inline">\(\beta_{0}\)</span> (ver Figura <a href="modelo-lineal-simple.html#fig:influyentes">1.8</a>(b) y la estimación de <span class="math inline">\(\sigma^{2}\)</span>.</p></li>
</ul>
<div class="figure" style="text-align: center"><span id="fig:influyentes"></span>
<img src="bookdownproj_files/figure-html/influyentes-1.png" alt="(a) Efecto de un punto influyente, la línea negra  es la estimación sin el punto A y la linea roja es la estimación incluyento el punto A. (b) Efecto de un punto atípico, la línea negra  es la estimación sin el punto B y la linea roja es la estimación incluyento el punto B." width="768" />
<p class="caption">
Figure 1.8: (a) Efecto de un punto influyente, la línea negra es la estimación sin el punto A y la linea roja es la estimación incluyento el punto A. (b) Efecto de un punto atípico, la línea negra es la estimación sin el punto B y la linea roja es la estimación incluyento el punto B.
</p>
</div>
<p>Los métodos para la detección de puntos atípicos e influyentes se presentarán en un capítulo posterior.</p>
<ul>
<li>Una fuerte relación entre dos variables no necesariamente implica que la relación entre las variables es de causa-efecto. Un modelo de regresión nos permite modelar variables que estén correlacionadas, pero no se puede concluir que, necesariamente, es una relación causal.</li>
</ul>

</div>
</div>
<h3>References</h3>
<div id="refs" class="references csl-bib-body hanging-indent">
<div id="ref-montgomery_introduction_2012" class="csl-entry">
Montgomery, Douglas C., Elizabeth A. Peck, and G. Geoffrey Vining. 2012. <em>Introduction to Linear Regression Analysis</em>. 5th ed. Wiley Series in Probability and Statistics 821. Hoboken, <span>NJ</span>: Wiley.
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="index.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="modelo-lineal-múltiple.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/AlvaroFlorez/MLG1/edit/master/01-RegresionSimple.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": "https://github.com/AlvaroFlorez/MLG1/blob/master/01-RegresionSimple.Rmd",
"text": null
},
"download": null,
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
